package com.xmx.credit_card.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Card {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.card_number
     *
     * @mbggenerated
     */
    private String cardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.card_amount
     *
     * @mbggenerated
     */
    private BigDecimal cardAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.card_point
     *
     * @mbggenerated
     */
    private Integer cardPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.card_type
     *
     * @mbggenerated
     */
    private String cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.inqpwd
     *
     * @mbggenerated
     */
    private String inqpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.acct
     *
     * @mbggenerated
     */
    private String acct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.card_number
     *
     * @return the value of card.card_number
     *
     * @mbggenerated
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.card_number
     *
     * @param cardNumber the value for card.card_number
     *
     * @mbggenerated
     */
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber == null ? null : cardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.card_amount
     *
     * @return the value of card.card_amount
     *
     * @mbggenerated
     */
    public BigDecimal getCardAmount() {
        return cardAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.card_amount
     *
     * @param cardAmount the value for card.card_amount
     *
     * @mbggenerated
     */
    public void setCardAmount(BigDecimal cardAmount) {
        this.cardAmount = cardAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.card_point
     *
     * @return the value of card.card_point
     *
     * @mbggenerated
     */
    public Integer getCardPoint() {
        return cardPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.card_point
     *
     * @param cardPoint the value for card.card_point
     *
     * @mbggenerated
     */
    public void setCardPoint(Integer cardPoint) {
        this.cardPoint = cardPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.card_type
     *
     * @return the value of card.card_type
     *
     * @mbggenerated
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.card_type
     *
     * @param cardType the value for card.card_type
     *
     * @mbggenerated
     */
    public void setCardType(String cardType) {
        this.cardType = cardType == null ? null : cardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.inqpwd
     *
     * @return the value of card.inqpwd
     *
     * @mbggenerated
     */
    public String getInqpwd() {
        return inqpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.inqpwd
     *
     * @param inqpwd the value for card.inqpwd
     *
     * @mbggenerated
     */
    public void setInqpwd(String inqpwd) {
        this.inqpwd = inqpwd == null ? null : inqpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.acct
     *
     * @return the value of card.acct
     *
     * @mbggenerated
     */
    public String getAcct() {
        return acct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.acct
     *
     * @param acct the value for card.acct
     *
     * @mbggenerated
     */
    public void setAcct(String acct) {
        this.acct = acct == null ? null : acct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.create_time
     *
     * @return the value of card.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.create_time
     *
     * @param createTime the value for card.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}