package com.xmx.credit_card.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Transaction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.acct
     *
     * @mbggenerated
     */
    private String acct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.card_number
     *
     * @mbggenerated
     */
    private String cardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.product
     *
     * @mbggenerated
     */
    private Long product;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.id
     *
     * @return the value of event.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.id
     *
     * @param id the value for event.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.amount
     *
     * @return the value of event.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.amount
     *
     * @param amount the value for event.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.acct
     *
     * @return the value of event.acct
     *
     * @mbggenerated
     */
    public String getAcct() {
        return acct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.acct
     *
     * @param acct the value for event.acct
     *
     * @mbggenerated
     */
    public void setAcct(String acct) {
        this.acct = acct == null ? null : acct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.card_number
     *
     * @return the value of event.card_number
     *
     * @mbggenerated
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.card_number
     *
     * @param cardNumber the value for event.card_number
     *
     * @mbggenerated
     */
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber == null ? null : cardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.product
     *
     * @return the value of event.product
     *
     * @mbggenerated
     */
    public Long getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.product
     *
     * @param product the value for event.product
     *
     * @mbggenerated
     */
    public void setProduct(Long product) {
        this.product = product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.create_time
     *
     * @return the value of event.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.create_time
     *
     * @param createTime the value for event.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}